import React, { useMemo, useState } from 'react';
import { useLMS } from '../../context/LMSContext';
import { FileCheck2, Clock, ArrowLeft, Trophy, Search, ShieldCheck } from 'lucide-react';

export const PracticeQuizPage = () => {
  const { quizzes, submitQuizResult, currentUser } = useLMS();
  const [search, setSearch] = useState(''); const [activeQuiz, setActiveQuiz] = useState(null); const [qIndex, setQIndex] = useState(0); const [answers, setAnswers] = useState({}); const [result, setResult] = useState(null);
  const filtered = useMemo(() => (quizzes || []).filter(q => q.status === 'published' && (!currentUser || (q.assignedStudents || []).some(s => String(s?.id || s?._id || s) === String(currentUser.id)))).filter(q => `${q.title} ${q.courseTitle} ${q.institution || ''}`.toLowerCase().includes(search.toLowerCase())), [quizzes, search, currentUser]);
  const start = q => { setActiveQuiz(q); setQIndex(0); setAnswers({}); setResult(null); };
  if (!activeQuiz) return <div className="space-y-5"><div><h1 className="text-2xl font-extrabold">Practice & Quizzes</h1><p className="text-sm text-slate-500 mt-1">Only quizzes assigned to your account are available.</p></div><div className="relative"><Search className="absolute left-3 top-3 w-4 h-4 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search your assigned quizzes..." className="w-full bg-white border rounded-2xl pl-10 p-3 text-sm"/></div><div className="grid sm:grid-cols-2 gap-5">{filtered.map(q=><div key={q.id} className="bg-white p-5 rounded-2xl border shadow-sm"><div className="flex justify-between"><FileCheck2 className="w-5 h-5 text-purple-600"/><span className="text-[10px] text-emerald-700 font-bold flex gap-1"><ShieldCheck className="w-3 h-3"/> Assigned</span></div><h3 className="font-bold mt-3">{q.title}</h3><p className="text-xs text-slate-500 mt-1">{q.courseTitle} • {q.questions?.length || 0} Questions • <Clock className="inline w-3 h-3"/> {q.durationMinutes} min</p><button onClick={()=>start(q)} className="w-full mt-4 py-2 bg-purple-700 text-white rounded-xl text-xs font-bold">Start Quiz</button></div>)}</div>{!filtered.length&&<div className="bg-white border rounded-2xl p-10 text-center text-sm text-slate-500">No assigned quiz matches your search.</div>}</div>;
  const question = activeQuiz.questions[qIndex];
  const next = async () => { if (qIndex < activeQuiz.questions.length - 1) return setQIndex(i=>i+1); const r = await submitQuizResult(activeQuiz.id, 0, 0, activeQuiz.questions.length, answers); if (r) setResult({correct:r.correctCount,total:r.totalCount,percentage:r.scorePercentage}); };
  if (result) { const passed=result.percentage >= (activeQuiz.passingScore||60); return <div className="max-w-lg mx-auto bg-white p-8 rounded-3xl border text-center space-y-4"><Trophy className="w-12 h-12 mx-auto text-amber-500"/><h2 className="text-xl font-extrabold">{passed?'Great Job!':'Keep Practicing'}</h2><p className="text-sm">You scored <b>{result.correct}/{result.total}</b> ({result.percentage}%)</p><button onClick={()=>setActiveQuiz(null)} className="px-4 py-2 bg-purple-700 text-white rounded-xl text-xs font-bold">Back to Quizzes</button></div>; }
  return <div className="max-w-2xl mx-auto space-y-5"><div className="flex items-center justify-between"><button onClick={()=>setActiveQuiz(null)} className="p-2"><ArrowLeft/></button><span className="text-xs font-bold">Question {qIndex+1} of {activeQuiz.questions.length}</span></div><div className="bg-white p-6 rounded-3xl border shadow-sm space-y-4"><h3 className="font-bold">{question.question}</h3>{question.options.map((opt,i)=><button key={i} onClick={()=>setAnswers(a=>({...a,[question.id]:i}))} className={`w-full text-left p-3.5 rounded-2xl border text-sm ${answers[question.id]===i?'bg-emerald-50 border-emerald-300 font-semibold':'bg-white border-slate-200'}`}><b className="mr-2">{String.fromCharCode(65+i)}.</b>{opt}</button>)}</div><button onClick={next} disabled={answers[question.id]===undefined} className="w-full py-3 bg-purple-700 disabled:bg-slate-200 text-white rounded-xl font-bold">{qIndex<activeQuiz.questions.length-1?'Next Question':'Submit Quiz'}</button></div>;
};
