import React, { useState } from 'react';
import { useLMS } from '../../context/LMSContext';
import { Plus, Trash2, Lock, Unlock } from 'lucide-react';

export const CourseManagerPage = () => {
  const { courses, addCourse, deleteCourse, updateModuleAccess } = useLMS();
  const [showAdd, setShowAdd] = useState(false);
  const [editingAccess, setEditingAccess] = useState(null);
  const [access, setAccess] = useState({});
  const [title,setTitle]=useState(''); const [category,setCategory]=useState('Web Development'); const [duration,setDuration]=useState('12 Weeks'); const [description,setDescription]=useState(''); const [videoUrl,setVideoUrl]=useState('');
  const create = async e => { e.preventDefault(); if(!title.trim()) return; await addCourse({title,category,price:0,originalPrice:0,duration,description:description||'Comprehensive course modules and lessons.',videoUrl,thumbnail:'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=600&auto=format&fit=crop&q=80'}); setShowAdd(false); setTitle(''); setDescription(''); };
  const openAccess = c => { setEditingAccess(c); setAccess(Object.fromEntries((c.modules||[]).map(m=>[m.moduleId,m.enabled!==false]))); };
  const saveAccess = async () => { await updateModuleAccess(editingAccess.id, access); setEditingAccess(null); };
  return <div className="space-y-6"><div className="flex justify-between items-start"><div><h1 className="text-2xl font-extrabold">Curriculum & Course Management</h1><p className="text-sm text-slate-500">Manage courses and control which modules are released to students.</p></div><button onClick={()=>setShowAdd(true)} className="px-4 py-2.5 bg-purple-700 text-white rounded-xl text-xs font-bold"><Plus className="inline w-4 h-4 mr-1"/>Add Course</button></div><div className="grid md:grid-cols-2 lg:grid-cols-3 gap-5">{courses.map(c=><div key={c.id} className="bg-white p-5 rounded-2xl border shadow-sm"><img src={c.thumbnail} className="w-full h-32 object-cover rounded-xl"/><h3 className="font-bold mt-3">{c.title}</h3><p className="text-xs text-slate-500 mt-1">{c.modules?.length||0} modules • {c.price>0?`₹${c.price}`:'Free'}</p><div className="grid grid-cols-2 gap-2 mt-4"><button onClick={()=>openAccess(c)} className="py-2 rounded-xl bg-purple-50 text-purple-700 text-xs font-bold">Module Access</button><button onClick={()=>window.confirm(`Delete ${c.title}?`)&&deleteCourse(c.id)} className="py-2 rounded-xl bg-red-50 text-red-600 text-xs font-bold"><Trash2 className="inline w-3.5 h-3.5 mr-1"/>Delete</button></div></div>)}</div>
  {showAdd&&<div className="fixed inset-0 z-50 bg-slate-900/60 flex items-center justify-center p-4"><form onSubmit={create} className="bg-white rounded-2xl p-6 max-w-md w-full space-y-3"><h2 className="font-extrabold">Create Course</h2><input required value={title} onChange={e=>setTitle(e.target.value)} placeholder="Course title" className="w-full border rounded-xl p-3"/><select value={category} onChange={e=>setCategory(e.target.value)} className="w-full border rounded-xl p-3"><option>Web Development</option><option>Python & AI</option><option>Tools & DevOps</option><option>Data Structures</option></select><input value={duration} onChange={e=>setDuration(e.target.value)} placeholder="Duration" className="w-full border rounded-xl p-3"/><input value={videoUrl} onChange={e=>setVideoUrl(e.target.value)} placeholder="Video URL" className="w-full border rounded-xl p-3"/><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Description" className="w-full border rounded-xl p-3"/><div className="flex justify-end gap-2"><button type="button" onClick={()=>setShowAdd(false)} className="px-4 py-2 rounded-xl bg-slate-100">Cancel</button><button className="px-4 py-2 rounded-xl bg-purple-700 text-white font-bold">Create</button></div></form></div>}
  {editingAccess&&<div className="fixed inset-0 z-50 bg-slate-900/60 flex items-center justify-center p-4"><div className="bg-white rounded-2xl p-6 max-w-xl w-full space-y-4"><div><h2 className="font-extrabold">Module Access — {editingAccess.title}</h2><p className="text-xs text-slate-500">Only an administrator can change this. Students can access released modules only.</p></div><div className="space-y-2 max-h-96 overflow-y-auto">{(editingAccess.modules||[]).map((m,i)=><div key={m.moduleId} className="flex items-center justify-between p-3 rounded-xl border"><div><b className="text-sm">{m.title||`Module ${i+1}`}</b><p className="text-[11px] text-slate-400">{m.lessons?.length||0} lessons</p></div><button onClick={()=>setAccess(a=>({...a,[m.moduleId]:!a[m.moduleId]}))} className={`px-3 py-2 rounded-xl text-xs font-bold flex items-center gap-1 ${access[m.moduleId]?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-500'}`}>{access[m.moduleId]?<><Unlock className="w-3.5 h-3.5"/>Released</>:<><Lock className="w-3.5 h-3.5"/>Locked</>}</button></div>)}</div><div className="flex justify-end gap-2"><button onClick={()=>setEditingAccess(null)} className="px-4 py-2 rounded-xl bg-slate-100">Cancel</button><button onClick={saveAccess} className="px-4 py-2 rounded-xl bg-purple-700 text-white font-bold">Save Access</button></div></div></div>}
  </div>;
};